// =============================
// Load Saved Result
// =============================
window.onload = function () {

    const details = localStorage.getItem("studentDetails");
    const result = localStorage.getItem("studentResult");

    if (details) {
        document.getElementById("studentDetails").innerHTML = details;
    }

    if (result) {
        document.getElementById("output").innerHTML = result;
    }

};

// =============================
// Calculate Result
// =============================
function runProgram() {

    let name = document.getElementById("name").value.trim();
    let roll = document.getElementById("roll").value.trim();
    let course = document.getElementById("course").value.trim();
    let age = document.getElementById("age").value;

    let m1 = Number(document.getElementById("m1").value);
    let m2 = Number(document.getElementById("m2").value);
    let m3 = Number(document.getElementById("m3").value);
    let m4 = Number(document.getElementById("m4").value);
    let m5 = Number(document.getElementById("m5").value);

    if (
        name === "" ||
        roll === "" ||
        course === "" ||
        age === "" ||
        isNaN(m1) ||
        isNaN(m2) ||
        isNaN(m3) ||
        isNaN(m4) ||
        isNaN(m5)
    ) {

        alert("Please fill all fields.");
        return;

    }

    let marks = [m1, m2, m3, m4, m5];

    for (let mark of marks) {

        if (mark < 0 || mark > 100) {

            alert("Marks must be between 0 and 100.");
            return;

        }

    }

    let total = m1 + m2 + m3 + m4 + m5;
    let average = total / 5;
    let percentage = average;

    let grade = "";
    let remarks = "";
    // =============================
// Grade & Remarks
// =============================

if (percentage >= 90) {
    grade = "A+";
    remarks = "Outstanding";
}
else if (percentage >= 80) {
    grade = "A";
    remarks = "Excellent";
}
else if (percentage >= 70) {
    grade = "B";
    remarks = "Very Good";
}
else if (percentage >= 60) {
    grade = "C";
    remarks = "Good";
}
else if (percentage >= 50) {
    grade = "D";
    remarks = "Pass";
}
else {
    grade = "F";
    remarks = "Fail";
}

let status = percentage >= 50 ? "PASS ✅" : "FAIL ❌";

let scholarship = percentage >= 85
    ? "Eligible"
    : "Not Eligible";

// =============================
// Student Details
// =============================

let details = `
<h2>Student Details</h2>

<p><b>Name:</b> ${name}</p>
<p><b>Roll Number:</b> ${roll}</p>
<p><b>Course:</b> ${course}</p>
<p><b>Age:</b> ${age}</p>
`;

// =============================
// Result
// =============================
let result = `
<h2>Student Grade Report</h2>

<p><b>Total Marks:</b> ${total}</p>
<p><b>Average:</b> ${average.toFixed(2)}</p>
<p><b>Percentage:</b> ${percentage.toFixed(2)}%</p>
<p><b>Grade:</b> ${grade}</p>
<p><b>Remarks:</b> ${remarks}</p>
<p><b>Status:</b> ${status}</p>
<p><b>Scholarship:</b> ${scholarship}</p>

<hr>

<p style="text-align:center;">
Generated by Student Grade Calculator
</p>
`;

// Display on screen
document.getElementById("studentDetails").innerHTML = details;
document.getElementById("output").innerHTML = result;

// Save in Local Storage
localStorage.setItem("studentDetails", details);
localStorage.setItem("studentResult", result);

}
// =============================
// Reset Form
// =============================
function resetForm() {

    document.getElementById("name").value = "";
    document.getElementById("roll").value = "";
    document.getElementById("course").value = "";
    document.getElementById("age").value = "";

    document.getElementById("m1").value = "";
    document.getElementById("m2").value = "";
    document.getElementById("m3").value = "";
    document.getElementById("m4").value = "";
    document.getElementById("m5").value = "";

    document.getElementById("studentDetails").innerHTML = "";
    document.getElementById("output").innerHTML = "";

    localStorage.removeItem("studentDetails");
    localStorage.removeItem("studentResult");

}

// =============================
// Dark Mode
// =============================
function toggleDarkMode() {
    document.body.classList.toggle("dark");
}

// =============================
// Print Result Only
// =============================
function printResult() {

    if (document.getElementById("output").innerHTML.trim() === "") {
        alert("Please calculate the result first.");
        return;
    }

    window.print();

}
